### ISSUE TITLE
Projekt URL not found

### ISSUE THREAD

**Issue by bountin** [branflake2267/Archetypes#71]
Looks like it changed to https://project-directory.appspot.com/ instead of http://project-manager-directory.appspot.com/.

**Comment by branflake2267** [comment]
yeah one of them was to long for something, so I shortened the sub domain up.

**Comment by branflake2267** [comment]
I think you submitted a Pull Request, and I think I hurried through the merge, but for some reason I don't see the commit in the list. I think I made a mistake, could you reopen that if I did? Sorry about that.

**Comment by bountin** [comment]
Hi, I think it was the URL in the github project description but I'm not sure as the issue is now some month old ...

**Comment by branflake2267** [comment]
Yeah sorry I missed that, I like to try to attend to them sooner. Thanks for pulling.
